services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sakshi-postgres
    environment:
      POSTGRES_DB: sakshi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tneural01
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - sakshi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Main Flask Application (API Gateway & Web UI)
  main-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.main
    container_name: sakshi-main-app
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Tneural01@localhost:5433/sakshi
      - TELEGRAM_BOT_TOKEN=7843300957:AAGVv866cPiDPVD0Wrk_wwEEHDSD64Pgaqs
      - TELEGRAM_CHAT_ID=-4835836048
      - DOCKER_MODE=true
    volumes:
      - ./config:/app/config
      - ./static:/app/static
      - ./templates:/app/templates
      - ./models:/app/models
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  # People Counter Processor
  people-counter-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile.people_counter
    container_name: sakshi-people-counter
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Tneural01@localhost:5433/sakshi
      - MAIN_APP_URL=http://localhost:5001
      - PROCESSOR_TYPE=people_counter
      - USE_PLACEHOLDER_FEED=false
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./static:/app/static
    depends_on:
      - main-app
    restart: unless-stopped
    # GPU disabled - running on CPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]


  # Kitchen Compliance Monitor
  kitchen-compliance-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile.kitchen_compliance
    container_name: sakshi-kitchen-compliance
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Tneural01@localhost:5433/sakshi
      - MAIN_APP_URL=http://localhost:5001
      - TELEGRAM_BOT_TOKEN=7843300957:AAGVv866cPiDPVD0Wrk_wwEEHDSD64Pgaqs
      - TELEGRAM_CHAT_ID=-4835836048
      - PROCESSOR_TYPE=kitchen_compliance
      - USE_PLACEHOLDER_FEED=false
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./static:/app/static
    depends_on:
      - main-app
    restart: unless-stopped
    # GPU disabled - running on CPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Queue Monitor Processor
  queue-monitor-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile.queue_monitor
    container_name: sakshi-queue-monitor
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Tneural01@localhost:5433/sakshi
      - MAIN_APP_URL=http://localhost:5001
      - PROCESSOR_TYPE=queue_monitor
      - USE_PLACEHOLDER_FEED=false
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./static:/app/static
    depends_on:
      - main-app
    restart: unless-stopped
    # GPU disabled - running on CPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Occupancy Monitor Processor
  occupancy-monitor-processor:
    build:
      context: .
      dockerfile: docker/Dockerfile.occupancy_monitor
    container_name: sakshi-occupancy-monitor
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Tneural01@localhost:5433/sakshi
      - MAIN_APP_URL=http://localhost:5001
      - TELEGRAM_BOT_TOKEN=7843300957:AAGVv866cPiDPVD0Wrk_wwEEHDSD64Pgaqs
      - TELEGRAM_CHAT_ID=-4835836048
      - PROCESSOR_TYPE=occupancy_monitor
      - USE_PLACEHOLDER_FEED=false
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./static:/app/static
      - ./test-videos:/app/test-videos 
    depends_on:
      - main-app
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  sakshi-network:
    driver: bridge

volumes:
  postgres_data:

